version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_chatbot
    ports:
      - "8000:8000"
    environment:
      # LLM Provider Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      
      # Application Configuration
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Optional: Mount source code for development
      # - ./src:/app/src
      # - ./static:/app/static
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
